apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sadebo/azure-aks-argocd-project.git
    targetRevision: main
    path: helm-charts/flask-app # Points to Helm chart
    helm:
      releaseName: flask-app
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # Auto-correct drift
    syncOptions:
    - CreateNamespace=true # Auto-create namespace if it doesn't exist
