replicaCount: 2

image:
  repository: parallelacr9875.azurecr.io/flask-app
  # tag: ""
  pullPolicy: IfNotPresent
  pullSecrets:
  - acr-auth

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  hosts:
  - host: flask.parallelservicesllc.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: flask-tls
    hosts:
    - flask.parallelservicesllc.com

env:
- name: REDIS_HOST
  value: redis.default.svc.cluster.local
- name: REDIS_PORT
  value: "6379"
