replicaCount: 2

image:
  repository: parallelacr9875.azurecr.io/flask-app
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  hosts:
  - host: flask.parallelservicesllc.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: flask-app-tls
    hosts:
    - flask.parallelservicesllc.com
