name: Destroy AKS + ArgoCD

on:
  workflow_dispatch:
    # manual trigger only (to avoid accidents)

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: dev # same environment as deploy, reuses secrets

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.5

    - name: Login to Azure
      run: |
        az login --service-principal \
          -u $ARM_CLIENT_ID \
          -p $ARM_CLIENT_SECRET \
          --tenant $ARM_TENANT_ID

    - name: Terraform Destroy (AKS + ACR)
      working-directory: terraform
      run: |
        terraform init
        terraform destroy -auto-approve

    - name: Terraform Destroy (Storage)
      working-directory: storage
      run: |
        terraform init
        terraform destroy -auto-approve
